In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('Data_Extract_From_Worldwide_Governance_Indicators.xlsx')

In [3]:
data.head()

,Country Name,Country Code,Series Name,2005,2010,2015,2018
0,Afghanistan,AFG,Control of Corruption,-1.44361,-1.63572,-1.34199,-1.49665
1,Afghanistan,AFG,Government Effectiveness,-1.21083,-1.45468,-1.32297,-1.45728
2,Afghanistan,AFG,Political Stability and Absence of Violence/Te...,-2.07093,-2.57915,-2.57122,-2.74673
3,Afghanistan,AFG,Regulatory Quality,-1.63737,-1.53286,-0.997371,-1.13263
4,Afghanistan,AFG,Rule of Law,-1.65867,-1.84544,-1.50404,-1.66848

In [6]:
data = pd.melt(data, id_vars=['Country Name','Country Code','Series Name'], var_name = 'Année', value_name = 'Note')
data.head()

,Country Name,Country Code,Series Name,Année,Note
0,Afghanistan,AFG,Control of Corruption,2005,-1.44361
1,Afghanistan,AFG,Government Effectiveness,2005,-1.21083
2,Afghanistan,AFG,Political Stability and Absence of Violence/Te...,2005,-2.07093
3,Afghanistan,AFG,Regulatory Quality,2005,-1.63737
4,Afghanistan,AFG,Rule of Law,2005,-1.65867

In [9]:
#data.pivot(index = [('Country Name','Country Code','Année')], columns = 'Series Name', values = 'Note')
data['Series Name'].unique()

array(['Control of Corruption', 'Government Effectiveness',
       'Political Stability and Absence of Violence/Terrorism',
       'Regulatory Quality', 'Rule of Law', 'Voice and Accountability'],
      dtype=object)

In [24]:
data = pd.crosstab([data['Country Name'],data['Country Code'],data['Année']],data['Series Name'], values=data.Note, aggfunc = sum)
data.reset_index(inplace = True)
data.head()

Series Name,Country Name,Country Code,Année,Control of Corruption,Government Effectiveness,Political Stability and Absence of Violence/Terrorism,Regulatory Quality,Rule of Law,Voice and Accountability
0,Afghanistan,AFG,2005,-1.44361,-1.21083,-2.07093,-1.63737,-1.65867,-1.12543
1,Afghanistan,AFG,2010,-1.63572,-1.45468,-2.57915,-1.53286,-1.84544,-1.40447
2,Afghanistan,AFG,2015,-1.34199,-1.32297,-2.57122,-0.997371,-1.50404,-1.11756
3,Afghanistan,AFG,2018,-1.49665,-1.45728,-2.74673,-1.13263,-1.66848,-0.99472
4,Albania,ALB,2005,-0.786193,-0.659452,-0.50714,-0.371874,-0.736336,0.0036718

In [ ]:
data.to_csv()